# This workflow will install the package and run the tests via unittest.

name: Tests

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test
    if: github.event.pull_request.merged == false

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Build and install package
        run: python -m pip install .

      - name: Run tests
        run: python -m unittest tests